import React, { useState, useCallback, useRef } from 'react';
import { generateSpeech } from './services/geminiService';
import { decode, decodeAudioData, audioBufferToWavBlob } from './utils/audioUtils';
import { SpeakerWaveIcon, PlayIcon, StopIcon, SparklesIcon, LoadingSpinnerIcon, WarningIcon, DownloadIcon } from './components/icons';

const voices = [
    { id: 'Zephyr', name: 'Man 1 (Zephyr)' },
    { id: 'Puck', name: 'Man 2 (Puck)' },
    { id: 'Charon', name: 'Man 3 (Charon)' },
    { id: 'Fenrir', name: 'Man 4 (Fenrir)' },
    { id: 'Kore', name: 'Woman (Kore)' },
];

const App: React.FC = () => {
  const [text, setText] = useState<string>('Hello! I am a voice generated by Google\'s Gemini model. Type some text here, choose a voice, and I will say it for you.');
  const [selectedVoice, setSelectedVoice] = useState<string>(voices[0].id);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [audioBuffer, setAudioBuffer] = useState<AudioBuffer | null>(null);
  const [audioBlob, setAudioBlob] = useState<Blob | null>(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);

  const audioContextRef = useRef<AudioContext | null>(null);
  const audioSourceRef = useRef<AudioBufferSourceNode | null>(null);

  const handleGenerateSpeech = useCallback(async () => {
    if (!text.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setAudioBuffer(null);
    setAudioBlob(null);
    if (audioSourceRef.current) {
        audioSourceRef.current.stop();
        setIsPlaying(false);
    }

    try {
      const base64Audio = await generateSpeech(text, selectedVoice);
      if (!base64Audio) {
        throw new Error('API did not return audio data.');
      }

      if (!audioContextRef.current) {
         audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 24000 });
      }
      const audioCtx = audioContextRef.current;
      const decodedData = decode(base64Audio);
      const buffer = await decodeAudioData(decodedData, audioCtx, 24000, 1);
      setAudioBuffer(buffer);

      const wavBlob = audioBufferToWavBlob(buffer);
      setAudioBlob(wavBlob);

    } catch (err) {
      console.error('Error generating speech:', err);
      setError(err instanceof Error ? err.message : 'An unknown error occurred.');
    } finally {
      setIsLoading(false);
    }
  }, [text, selectedVoice, isLoading]);

  const handlePlayAudio = () => {
    if (!audioBuffer) return;

    if (isPlaying && audioSourceRef.current) {
      audioSourceRef.current.stop();
      setIsPlaying(false);
      return;
    }

    if (!audioContextRef.current) return;
    
    if (audioContextRef.current.state === 'suspended') {
      audioContextRef.current.resume();
    }

    const source = audioContextRef.current.createBufferSource();
    source.buffer = audioBuffer;
    source.connect(audioContextRef.current.destination);
    source.onended = () => {
        setIsPlaying(false);
        audioSourceRef.current = null;
    };
    source.start();
    audioSourceRef.current = source;
    setIsPlaying(true);
  };
  
  const handleDownload = () => {
    if (!audioBlob) return;
    const url = URL.createObjectURL(audioBlob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `gemini-speech-${selectedVoice.toLowerCase()}.wav`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };


  return (
    <div className="min-h-screen bg-gray-900 flex flex-col items-center justify-center p-4 font-sans">
      <div className="w-full max-w-2xl bg-gray-800 rounded-2xl shadow-2xl p-6 md:p-8 space-y-6 border border-gray-700">
        <header className="text-center">
          <div className="flex justify-center items-center gap-3">
            <SpeakerWaveIcon className="w-8 h-8 text-indigo-400" />
            <h1 className="text-3xl md:text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-500">
              Gemini Text-to-Speech
            </h1>
          </div>
          <p className="mt-2 text-gray-400">Convert your text into lifelike speech.</p>
        </header>

        <div>
            <label htmlFor="voice-select" className="block text-sm font-medium text-gray-400 mb-2">
                Choose a voice:
            </label>
            <select
                id="voice-select"
                value={selectedVoice}
                onChange={(e) => setSelectedVoice(e.target.value)}
                disabled={isLoading}
                className="w-full p-3 bg-gray-900 border-2 border-gray-700 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors duration-200 text-gray-200"
            >
                {voices.map((voice) => (
                    <option key={voice.id} value={voice.id}>
                        {voice.name}
                    </option>
                ))}
            </select>
             <p className="text-xs text-gray-500 mt-1">Note: A dedicated child's voice is not available in this selection.</p>
        </div>

        <div className="relative">
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Enter text to convert to speech..."
            className="w-full h-48 p-4 bg-gray-900 border-2 border-gray-700 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors duration-200 resize-none text-gray-200 placeholder-gray-500"
            disabled={isLoading}
          />
        </div>

        {error && (
          <div className="flex items-center gap-3 bg-red-900/50 text-red-300 p-3 rounded-lg border border-red-800">
            <WarningIcon className="w-5 h-5 flex-shrink-0"/>
            <p className="text-sm">{error}</p>
          </div>
        )}
        
        <div className="flex flex-col sm:flex-row gap-4">
          <button
            onClick={handleGenerateSpeech}
            disabled={isLoading || !text.trim()}
            className="w-full sm:w-auto flex-grow flex items-center justify-center gap-3 px-6 py-3 bg-indigo-600 text-white font-semibold rounded-lg shadow-md hover:bg-indigo-700 disabled:bg-gray-600 disabled:cursor-not-allowed transition-all duration-300 transform hover:scale-105 disabled:scale-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-indigo-500"
          >
            {isLoading ? (
                <>
                    <LoadingSpinnerIcon className="w-5 h-5" />
                    <span>Generating...</span>
                </>
            ) : (
                <>
                    <SparklesIcon className="w-5 h-5"/>
                    <span>Generate Speech</span>
                </>
            )}
          </button>

          {audioBuffer && (
            <>
                <button
                onClick={handlePlayAudio}
                className="w-full sm:w-auto flex items-center justify-center gap-3 px-6 py-3 bg-green-600 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-green-500"
                >
                {isPlaying ? (
                    <>
                        <StopIcon className="w-5 h-5" />
                        <span>Stop</span>
                    </>
                ) : (
                    <>
                        <PlayIcon className="w-5 h-5" />
                        <span>Play Audio</span>
                    </>
                )}
                </button>
                <button
                    onClick={handleDownload}
                    className="w-full sm:w-auto flex items-center justify-center gap-3 px-6 py-3 bg-gray-600 text-white font-semibold rounded-lg shadow-md hover:bg-gray-700 transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-gray-500"
                >
                    <DownloadIcon className="w-5 h-5" />
                    <span>Download WAV</span>
                </button>
            </>
          )}
        </div>
      </div>
      <footer className="text-center mt-8 text-gray-500 text-sm">
        <p>Powered by Google Gemini.</p>
      </footer>
    </div>
  );
};

export default App;